
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Dec 10 18:53:34 MST 2020
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LINEA = 23;
  public static final int Y = 10;
  public static final int CADENA = 6;
  public static final int Numero = 21;
  public static final int LOS = 13;
  public static final int PEDIDO = 8;
  public static final int ERROR = 24;
  public static final int POR = 19;
  public static final int LAS = 12;
  public static final int Coma = 22;
  public static final int CANT_UN = 14;
  public static final int LA = 9;
  public static final int QUIERO = 3;
  public static final int OYE = 4;
  public static final int EOF = 0;
  public static final int FAVOR = 20;
  public static final int PEPSI = 18;
  public static final int DE = 17;
  public static final int SANJI = 2;
  public static final int error = 1;
  public static final int TRAER = 5;
  public static final int CANT_UNA = 15;
  public static final int EL = 11;
  public static final int HACER = 7;
  public static final int CANT_PLURALES = 16;
}

