
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jan 07 19:05:52 MST 2021
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PIE_QUESO = 47;
  public static final int PIE_MORA = 46;
  public static final int NUEVE = 73;
  public static final int PIE_LIMON = 44;
  public static final int DOCE = 76;
  public static final int Coma = 26;
  public static final int PIE_FRESA = 45;
  public static final int VICTORIA = 55;
  public static final int SIETE = 71;
  public static final int CUCHARAS = 19;
  public static final int COCA_COLA = 54;
  public static final int LEER = 63;
  public static final int SANJI = 2;
  public static final int POR = 23;
  public static final int FRUTA_CARAMELO = 42;
  public static final int LIMONADA = 52;
  public static final int NARANJADA = 53;
  public static final int CORONA = 59;
  public static final int ERROR = 28;
  public static final int LA = 10;
  public static final int JUGO = 57;
  public static final int LOS = 14;
  public static final int PEPSI = 22;
  public static final int VAMPIRO = 58;
  public static final int ONCE = 75;
  public static final int HACER = 7;
  public static final int EL = 12;
  public static final int TENEDORES = 20;
  public static final int PEDIDO = 8;
  public static final int SERVILLETAS = 21;
  public static final int SUSHI_RES = 35;
  public static final int CARTA = 65;
  public static final int CANT_UN = 15;
  public static final int Y = 11;
  public static final int HELADO_CACAO = 43;
  public static final int CINCO = 69;
  public static final int FAVOR = 24;
  public static final int LINEA = 27;
  public static final int HAMBURGUESA_ARROZ = 38;
  public static final int DE = 17;
  public static final int QUIERO = 3;
  public static final int CHURROS = 48;
  public static final int DOS = 66;
  public static final int VASOS = 18;
  public static final int LAS = 13;
  public static final int CATORCE = 78;
  public static final int TRAER = 5;
  public static final int EOF = 0;
  public static final int MOSTRAR = 61;
  public static final int VER = 62;
  public static final int PIÑA_COLADA = 56;
  public static final int Numero = 25;
  public static final int BOMBAZO = 37;
  public static final int SUSHI_CAMARON = 29;
  public static final int TERIYAKI = 40;
  public static final int OYE = 4;
  public static final int SEIS = 70;
  public static final int FONDANT = 60;
  public static final int MENU = 64;
  public static final int error = 1;
  public static final int HELADO_VAINILLA = 41;
  public static final int MESAD = 33;
  public static final int MESAC = 32;
  public static final int MESAB = 31;
  public static final int MESAA = 30;
  public static final int QUINCE = 79;
  public static final int DIEZ = 74;
  public static final int CANT_UNA = 16;
  public static final int CUATRO = 68;
  public static final int EXPRESSO = 50;
  public static final int MARTINI = 51;
  public static final int OCHO = 72;
  public static final int CAMARONITO = 36;
  public static final int CUENTA = 6;
  public static final int TRECE = 77;
  public static final int SUSHI_POLLO = 34;
  public static final int LISTO = 9;
  public static final int ADIOS = 39;
  public static final int TRES = 67;
  public static final int CAFE = 49;
}

