
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Dec 11 14:28:49 MST 2020
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SANJI = 2;
  public static final int Coma = 22;
  public static final int Y = 10;
  public static final int PIE_MORA = 40;
  public static final int DE = 17;
  public static final int OYE = 4;
  public static final int MARTINI = 46;
  public static final int POR = 19;
  public static final int MAR_TIERRA = 32;
  public static final int LAS = 12;
  public static final int HELADO_VAINILLA = 35;
  public static final int SUSHI_POLLO = 26;
  public static final int PIÑA_COLADA = 51;
  public static final int BOMBAZO = 29;
  public static final int EXPRESSO = 45;
  public static final int CANT_UN = 14;
  public static final int CORONA = 54;
  public static final int COCA_COLA = 49;
  public static final int PEPSI = 18;
  public static final int CANT_PLURALES = 16;
  public static final int CAFE = 44;
  public static final int TRES_QUESOS = 31;
  public static final int VAMPIRO = 53;
  public static final int EOF = 0;
  public static final int HELADO_CACAO = 37;
  public static final int LA = 9;
  public static final int SUSHI_RES = 27;
  public static final int JUGO = 52;
  public static final int error = 1;
  public static final int LOS = 13;
  public static final int CADENA = 6;
  public static final int CHURROS = 42;
  public static final int HAMBURGUESA_ARROZ = 33;
  public static final int PIE_LIMON = 38;
  public static final int ERROR = 24;
  public static final int FONDANT = 55;
  public static final int NARANJADA = 48;
  public static final int EL = 11;
  public static final int CANT_UNA = 15;
  public static final int DULCE_LECHE = 43;
  public static final int PIE_FRESA = 39;
  public static final int TRAER = 5;
  public static final int CIELO_MAR_TIERRA = 30;
  public static final int PIE_QUESO = 41;
  public static final int CAMARONITO = 28;
  public static final int HACER = 7;
  public static final int TERIYAKI = 34;
  public static final int LIMONADA = 47;
  public static final int PEDIDO = 8;
  public static final int FRUTA_CARAMELO = 36;
  public static final int VICTORIA = 50;
  public static final int SUSHI_CAMARON = 25;
  public static final int FAVOR = 20;
  public static final int Numero = 21;
  public static final int QUIERO = 3;
  public static final int LINEA = 23;
}

